# Conditional Expectation and the BLP

Let us roll two dice, and define random variables $X$ and $Y$ as the difference and sum of the face-values, respectively. Depending on what nature decides to choose when the dice are rolled, the random variable $X$ can output a number from $\{-5,-2,-1,0,1,2,3,4,5\}$ and $Y$ a number from $\{2,3,\ldots,12\}$. 

If $X=5$, then the face-values are $(6,1)$f

## CEF Bivariate


## (Optional) CEF Multivariate

:::{.theorem #cef name="Characterization of CEF"}
If \ $\E{Y^2}<\infty$ and $\v{X}$ is a random vector such that $Y=m(\v{X})+e$, then the following statements are equivalent:  
1. $m(\v{X})=\E{Y|\v{X}}$, the CEF of $Y$ given $\v{X}$   
2. $\E{e|\v{X}}=0$
:::



## Best Linear Predictor

Let $Y$ be a random variable and $\v{X}$ be a random vector of $k$ variables. We denote the **best linear predictor** of $Y$ given $\v{X}$ by $\mathscr{P}[Y|\v{X}]$. It's also called the **linear projection** of $Y$ on $\v{X}$. 

::: {.theorem #blp name="Best Linear Predictor"}
Under the following assumptions

1. $\E{Y^2}<\infty$
2. $\E{||\bf{X}||^2}<\infty$
3. $\m{Q}_{\bf{XX}}\stackrel{\text{def}}{=}\E{\v{X}^T\v{X}}$ is positive-definite

the best linear predictor exists uniquely, and has the form
$$
\mathscr{P}[Y|\v{X}]=\v{X}\v{\beta},
$$
where $\v{\beta}=\left(\E{\v{X}^T\v{X}}\right)^{-1}\m{E}[\v{X}^TY]$ is a column vector.
:::

In the following theorem, we show that the BLP error is *uncorrelated* to the explanatory variables.

::: {.theorem  #blperror name="Best Linear Predictor Error"}
If the BLP exists, the linear projection error $\eps=Y-\mathscr{P}[Y|\v{X}]$ follows the following properties:

1. $\m{E}[\v{X}^T\eps]=\v{0}$
2. moreover, $\m{E}[\eps]=0$ if 
$\v{X}=\begin{bmatrix}1 & X_{[1]} & \ldots & X_{[k]} \end{bmatrix}$ contains a constant.
:::